# Generated by Django 3.2.6 on 2021-08-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
